[package]
name = "lucita"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = {version = "0.11", features = ["native-tls"]}
http = "0.2"
base64 = "0.13"
log = "0.4"
ethereum-types = "0.10"

[dev-dependencies]
dotenv = "0.15"
