[package]
name = "lucita"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.11"
mio = {version = "0.7", features = ["os-poll", "net"]}
native-tls = "0.2"
http = "0.2"
base64 = "0.13"
log = "0.4"
dns-lookup = "1.0"