[package]
name = "lucita"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = {version = "0.12", features = ["native-tls"]}
http = "0.2"
base64 = "0.13"
log = "0.4"
ethereum-types = "0.10"
hex = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
crossbeam-channel = "0.5"

[dev-dependencies]
dotenv = "0.15"
lazy_static = "1.4"
