on: [push, pull_request]

name: Ethane Rust

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-latest
    services:
      ganache:
        image: pumpkinseed/ganache-fix
        ports:
          - 8545:8545
        env:
          WEB3_FORK_URL: https://mainnet.infura.io/v3/3b7abf15a83f4c37a0745dca3a1b400b
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Dependencies
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
      